### ISSUE TITLE
support for adding pecha repo `description` during creation

### ISSUE THREAD

**Issue by 10zinten** [OpenPecha/Toolkit#114]

**Comment by eroux** [comment]
@10zinten what would you like to put in the description?

**Comment by 10zinten** [comment]
@NT suggested to add, `title`, `author`, `source_id`, `work_id` etc. which are found in `source_metadata` of `meta.yml`. I think It's mainly to be able search pecha from github search, since github indexes the repo description.

actually I have already implemented here, just forgot to close the issue.

https://github.com/OpenPecha/Toolkit/blob/master/openpecha/core/pecha.py#L64-L70
