### ISSUE TITLE
wrong base / volume correspondence

### ISSUE THREAD

**Issue by eroux** [OpenPecha/Toolkit#137]
in https://github.com/OpenPecha/P000525 layer `v001` is associated with `bdr:I1KG2126` (volume 1), while it's in fact the OCR of `bdr:I1KG13691` (volume 11). Given that we have the Google OCR of each image it's probably easy to recover which volume should be associated with which base layer

**Comment by 10zinten** [comment]
sure, I will have @ta4tsering look over it

**Comment by ta4tsering** [comment]
I will correct the volumes and ocr the missing volumes from 13 to 33

**Comment by eroux** [comment]
let's close this and expect it will be fixed in the next OCR reimport round
