### ISSUE TITLE
add legacy_id field in meta.yml and bases

### ISSUE THREAD

**Issue by eroux** [OpenPecha/Toolkit#165]
BDRC needs to have fully stable URLs, and since the URLs are constructed based on the OpenPecha IDs, if these change (which is really not good but... it happened) we need to have a way to redirect the old id to the new one. The proposal here is to add a `legacy_id` property with the legacy one.  For instance for https://github.com/Openpecha-Data/IA3E40644 it would be `P000009`.

Ideally the same would happen for all the base layers too (also in `meta.yml`)

**Comment by ta4tsering** [comment]
so that means, for example:  IA3E40644's meta.yml will have legacy_id: P000009 right ?

**Comment by eroux** [comment]
yes
