### ISSUE TITLE
Renaming OpenPecha-Toolkit to OpenPecha

### ISSUE THREAD

**Issue by evanyerburgh** [OpenPecha/Toolkit#172]
**Is your feature request related to a problem? Please describe.**

- Title is too complicated.
- [OpenPecha code library](https://github.com/OpenPecha/OpenPecha-Toolkit/tree/master/openpecha) directory is called OpenPecha.
- Best practice is to name the repo with the core code library after the project.

**Describe the solution you'd like**
Change repo name to OpenPecha.

**Additional context**
See discussion #171

**Comment by 10zinten** [comment]
since the name OpenPecha represent the whole organization, having our toolkit repo named OpenPecha sounds confusing. Basically it just a toolkit therefore @ngawangtrinley decided to call it just "Toolkit"
