### ISSUE TITLE
Adding Github Actions to deploy website 

### ISSUE THREAD

**Issue by evanyerburgh** [OpenPecha/Toolkit#173]
**Is your feature request related to a problem? Please describe.**
- Changes to OpenPecha-Toolkit docs don't automatically update on [the website](https://docs.openpecha.org).
- Currently you have to [run a local script to update Mkdocs](https://www.mkdocs.org/user-guide/deploying-your-docs/). This adds an extra step, though, and the extra step discourages team members from updating often.

**Describe the solution you'd like**
Use Github Actions to automatically deploy changes to OpenPecha-Toolkit docs on [the website](https://docs.openpecha.org)

**Comment by 10zinten** [comment]
fix https://github.com/OpenPecha/Toolkit/blob/master/.github/workflows/publish.yaml#L53-L78
