### ISSUE TITLE
option to remove overlap duplication

### ISSUE THREAD

**Issue by eroux** [OpenPecha/Toolkit#220]
there should be an option in the ocr import pipeline to detect and remove duplicates as in

https://github.com/OpenPecha/OCR-Pipelines/issues/8

This should be relatively (!) straightforward by looking at pixel coordinates within a line and either:
- remove everything that has a big enough overlap (this is the best but more complex option)
- remove everything that goes back horizontally

**Comment by ta4tsering** [comment]
okay I will look into it
