### ISSUE TITLE
NorbuKetaka batch2

### ISSUE THREAD

**Issue by eroux** [OpenPecha/Toolkit#241]
This is a follow-up of

https://github.com/OpenPecha/Toolkit/issues/208

I've uploaded the files of the new (and likely final) batch on 

s3://ocr.bdrc.io/NorbuKetaka2/

let's have `batch-0001` for the batch id, and the following `info.json`

```json
{
   "timestamp": "2023-02-01T00:00:00Z"
}
```

**Comment by jungtop** [comment]
@eroux  Do you mean to create new opf for the NorbuKetaka2?

**Comment by eroux** [comment]
Yes

**Comment by jungtop** [comment]
Hey can u checkout the [sample opf](https://github.com/jungtop/I439E78F7.git).In the [software_id](https://github.com/jungtop/I439E78F7/blob/main/I439E78F7.opf/meta.yml#L8) in meta should it be norbuketaka2 or as before?

**Comment by eroux** [comment]
thanks! `software_id` should be as before, I'll look at the sample in a moment

**Comment by eroux** [comment]
oh sorry I realize I forgot to change the `batch_id` in my initial comment (my bad), it should be `batch-0002`

**Comment by eroux** [comment]
let's have `last_modified` set to  `2023-02-01T00:00:00Z`, but other than that it looks good, thanks!

**Comment by jungtop** [comment]
ok then i have to reimport the files to s3

**Comment by eroux** [comment]
oh, never mind then, having `batch-0001` is not a big deal, we can live with that

**Comment by jungtop** [comment]
Hey I have updated the catalog over [here](https://github.com/OpenPecha-Data/catalog/blob/master/data/Norbu-Ketaka2/pechas.csv).But for the file `Works/cf/W1PD133164/norbuketaka2/batch-0002/W1PD133164-I4PD2795.csv` the work id W1PD133164 does not have image group id I4PD2795.

**Comment by eroux** [comment]
thanks a lot!

It appears that in that case `W1PD133164` should be instead `W1PD133161` so the file should be merged with `W1PD133161-I4PD2795.csv`. Are there other cases like this?

Also, the point of `software_id` is to indicate the s3 folder, and it should be `norbuketaka`, not `norbuketaka2`, so please move the files on s3 (the opf files look good)

I'll go ahead and import the opf files, I'll tell you if I run in any trouble

**Comment by jungtop** [comment]
No that file is the only issue in batch-0002.
