### ISSUE TITLE
NorbuKetaka batch 3

### ISSUE THREAD

**Issue by eroux** [OpenPecha/Toolkit#263]
follow up on #208 here's the final batch of the NorbuKetaka project: http://eroux.fr/BDRC_Cleaned_Data_08052023_Queenie_Luo-20230806T080255Z-001.zip

batch 1: 1.9M lines
batch 2: 7.8M lines
batch 3: 4.1M lines

**Comment by kaldan007** [comment]
@eroux Norbu kateka batch 3 has been imported to Openpecha data. Here is the updated [catalog](https://github.com/OpenPecha-Data/catalog/blob/master/data/Norbu-Ketaka/pechas.csv)

**Comment by eroux** [comment]
oh that's great, thanks a lot!

**Comment by eroux** [comment]
@kaldan007 I'm looking at `ICB83899F`, specifically `ICB83899F.opf/base/I2PD18407.txt`, it doesn't have exactly the same format as the other opfs, which usually have two new line characters at every page change. Can you update them? Thanks

**Comment by kaldan007** [comment]
sure will do that
