### ISSUE TITLE
wrong timestamp in ocr_info in meta.yml

### ISSUE THREAD

**Issue by eroux** [OpenPecha/Toolkit#273]
I randomly looked at https://github.com/OpenPecha-Data/I6EBD6074/blob/master/I6EBD6074.opf/meta.yml#L9 and the value is different from the timestamp indicated in s3://ocr.bdrc.io/Works/a2/W00EGS1017419/google_books/batch_2022/info.json  , please make it the same, or even better, translated to ISO8601 standard format

**Comment by eroux** [comment]
related: https://github.com/buda-base/ao-google-books/issues/75

**Comment by kaldan007** [comment]
I have used the info.json to batch 02 onwards.
